### PR TITLE
Update embuild to 0.31.4 in template files

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for the update. Is there any reason for the PR being a draft?

**Comment by ivmarkov** [comment]
@kubo39 @SergioGasquez I don't mind this update, but I'm not sure what it solves? 
* On a first crate generation, anyway the `embuild` latest patch-level version would be downloaded and used, i.e. 0.31.4, NOT 0.31.3
* For older crates, you can always do `cargo update`

We are talking upgrading to a patch release here, which is anyway kinda automatic, as per ^^^
In fact, these days I often even tend not to specify the crate patch versions anymore.

Correct me if I'm wrong.

**Comment by SergioGasquez** [comment]
> I don't mind this update, but I'm not sure what it solves?

It does solve anything IMO, just updates the version in a explicitly way, as you mentioned, its the same as its only a patch update.

**Comment by SergioGasquez** [comment]
This can be closed as https://github.com/esp-rs/esp-idf-template/pull/209/ already bumps `embuild`

**Pull request closed without merging**
