### PR TITLE
Change defaults prompt to advanced

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Change defaults prompt to advanced
- Add `convertTol` Wokwi feature

See https://github.com/esp-rs/esp-template/issues/89

### CODE REVIEW

**Review by MabezDev — APPROVED** [review]
LGTM, thanks for implementing this! I guess the master failures shouldn't block this being merged.

**Comment by ivmarkov** [comment]
@MabezDev Since you mention the `master` failures... the Espressif C folks seemingly [removed the `UART_NUM_MAX` def from the public header of the `uart` driver](https://github.com/espressif/esp-idf/commit/921713fff40fa76dd89564f7dd22121ca4ce7a94#diff-d2a94ef90c117b12b291228c3ac68130a335c0deda7b8ec2ae4cf6f29b42065eL23). Oddly enough, it is mentioned in the methods' documentation.

Any idea what is going on?

**Comment by ivmarkov** [comment]
I mean, I can switch the code to use `SOC_UART_NUM` instead, but it still feels weird...

**Comment by MabezDev** [comment]
Seems like it was changed from a `#define` to an enum for the C drivers usage: https://github.com/espressif/esp-idf/blob/67552c31dac8cd94fb0d63192a538f4f984c5b6e/components/hal/include/hal/uart_types.h#L21.

I guess its easiest for us to just use `SOC_UART_NUM`?

**Comment by ivmarkov** [comment]
Yeah but it does not seem to be an intended change. I submitted a bug here: https://github.com/espressif/esp-idf/issues/11752

**Pull request merged**
