### PR TITLE
Enable CI for v4.4

### PR DESCRIPTION
**Pull request by SergioGasquez**

### CODE REVIEW

**Comment by ivmarkov** [comment]
@SergioGasquez As you can see, this does not work. I no longer remember who has removed it, but restoring the build for V4.4 would require a bit more effort.

**Comment by ivmarkov** [comment]
Yeah. I now remember - this has regressed when we have introduced the MCUs which are supported in ESP IDF 5.1+ only: esp32c2, esp32p4, esp32c5 and so on.

For 4.4, we have to only run the CI with the MCUs supported by it: esp32, esp32s2/s3, and esp32c3, I think

**Comment by SergioGasquez** [comment]
Oh yes! That was dumb from my side, I did the changes onto the CI so we have several jobs:
- cargo-checks-v5: Checks master and release/v5.1
- cargo-checks-v4: Checks release/v4.4
- container-check: Builds a v4.4 template project on the container
Every step only runs for the supported targets.

**Comment by ivmarkov** [comment]
Thanks! I'll just merge.

**Pull request merged**
