### PR TITLE
Update to the new release

### PR DESCRIPTION
**Pull request by ivmarkov**

### CODE REVIEW

**Review by SergioGasquez — CHANGES_REQUESTED** [review]
Seems like the MSRV is now 1.75 while in [CI we use 1.71](https://github.com/esp-rs/esp-idf-template/actions/runs/7669461993/workflow?pr=182#L51)

**Comment by ivmarkov** [comment]
> Seems like the MSRV is now 1.75 while in [CI we use 1.71](https://github.com/esp-rs/esp-idf-template/actions/runs/7669461993/workflow?pr=182#L51)

Indeed. Shall we just remove the version string from there? This way it would be always compiled against the latest Rust version available?

**Comment by SergioGasquez** [comment]
> Indeed. Shall we just remove the version string from there? This way it would be always compiled against the latest Rust version available?

Yes, I think that would be better. Regarding https://github.com/esp-rs/esp-idf-template/pull/182/commits/88d0ef74950f6aeca20cfaba1be1faa45aae3956, the tag `1.5` already points to the latest patch release, so I would also recommend using `1.5` instead of the pointing to the latest "full" version

**Comment by ivmarkov** [comment]
> > Indeed. Shall we just remove the version string from there? This way it would be always compiled against the latest Rust version available?
> 
> Yes, I think that would be better. Regarding [88d0ef7](https://github.com/esp-rs/esp-idf-template/commit/88d0ef74950f6aeca20cfaba1be1faa45aae3956), the tag `1.5` already points to the latest patch release, so I would also recommend using `1.5` instead of the pointing to the latest "full" version

Ok. I just copied from somewhere, but will revert.

**Comment by ivmarkov** [comment]
> > > Indeed. Shall we just remove the version string from there? This way it would be always compiled against the latest Rust version available?
> > 
> > 
> > Yes, I think that would be better. Regarding [88d0ef7](https://github.com/esp-rs/esp-idf-template/commit/88d0ef74950f6aeca20cfaba1be1faa45aae3956), the tag `1.5` already points to the latest patch release, so I would also recommend using `1.5` instead of the pointing to the latest "full" version
> 
> Ok. I just copied from somewhere, but will revert.

Reverted. You need to squash prior to merging.

**Comment by ivmarkov** [comment]
Sorry for the `vfs` hiccup - did not anticipate that. :) For now, I've enabled the `vfs` component in the cmake build. Next patch release of `esp-idf-svc` will have that addressed.

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for updating this!

**Pull request merged**
