### PR TITLE
Add the 64bit time_t flag when targeting v5

### PR DESCRIPTION
**Pull request by MabezDev**

### CODE REVIEW

**Review by ivmarkov — APPROVED** [review]
I think this change is OK. But given that ESP IDF 5 was already released, we might want to extend the `esp-idf-template` to support the 5.0 released version as well. And then the "if" for this flag would be a bit extended too.

Further on, we need to support this flag in the cmake-first build as well, but I guess this can be a separate PR.

**Comment by MabezDev** [comment]
Good points, will add cmake support and look at adding v5 support too.

**Comment by MabezDev** [comment]
I don't think V5.0 is fully released yet, at least there is no tag or release on GitHub so will defer adding those options to another PR.

**Comment by ivmarkov** [comment]
Indeed there is no `v5.0` tag, yet there is a release branch? 
`https://github.com/espressif/esp-idf/tree/release/v5.0`

**Comment by ivmarkov** [comment]
And docu: https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/get-started/index.html

**Comment by ivmarkov** [comment]
But I agree - this could be a separate PR.

**Comment by MabezDev** [comment]
> https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/get-started/index.html

At the top of those docs says v5.0 is a pre release version, so I'll defer for now until its properly released.

**Pull request merged**
